project_2_dvd_rentals:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT_ID") }}'

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: '{{ env_var("SNOWFLAKE_ROLE") }}'
      database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
      warehouse: '{{ env_var("SNOWFLAKE_WAREHOUSE") }}'
      schema: DVD_RENTALS_SNOWFLAKE
      threads: 1
